### ISSUE TITLE
Wordpress install root directory

### ISSUE THREAD

**Issue by ltarasiewicz** [miya0001/vccw#47]
Hi,
First of all, thank you for this great tool. 

Is it possible to change the wordpress install root directory? I just want to have Wordpress installed on VM in a different directory than "wordpress".  Will this change of directory be reflected in my local file system (synced folders)?

I look forward to your advice.

Thank you.

**Comment by richardadalton** [comment]
Sorry, this is probably an insanely noobie question, but,
when I vagrant ssh into this, I get into the vagrant folder as I'd expect, but I'd expect that to map to the folder on my host os that has the vagrantfile. Instead I see an empty vagrant folder. If I create a file in that vagrant folder (i.e. in the vagrant box) I can't find it in my Host OS.

Is there some magic happening?

**Comment by richardadalton** [comment]
Actually forget I asked. I can see in the Vagrantfile that www/wordpress is synced to var/www/wordpress

Like I said.   Noob

**Comment by miya0001** [comment]
Please try following.

```
vagrant plugin install vagrant-vbguest
```

**Comment by miya0001** [comment]
Hi @ltarasiewicz,

We've added a constant DOCUMENT_ROOT, so you can change document root directory. :)
