### ISSUE TITLE
I want to install WordPress to sub directory.

### ISSUE THREAD

**Issue by showw** [miya0001/vccw#52]
Hi, Thanks for great tool.

I have a question.
I have tried vccw many times,but I sometimes succeed and sometimes fail by using same vagrant file.

I added vagrantfile as follows:

WP_LANG="ja"
SITE_URL="/wp"
WP_HOSTNAME="test0114.local”

After that, vagrant up

——————————————————

MatsuoShoko-no-MacBook-Pro:repos showw$ cd 0114
MatsuoShoko-no-MacBook-Pro:0114 showw$ ls
Gemfile				Vagrantfile.theme-review
Gemfile.lock			cookbooks
README.md			provision
Rakefile			site-cookbooks
Vagrantfile			spec
MatsuoShoko-no-MacBook-Pro:0114 showw$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'miya0001/vccw'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'miya0001/vccw' is up to date...
==> default: Setting the name of the VM: 0114_default_1421196090974_87941
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Error: Connection timeout. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /Users/showw/repos/0114
    default: /var/www/wordpress => /Users/showw/repos/0114/www/wordpress
    default: /tmp/vagrant-chef-1/chef-solo-1/cookbooks => /Users/showw/repos/0114/cookbooks
    default: /tmp/vagrant-chef-1/chef-solo-2/cookbooks => /Users/showw/repos/0114/site-cookbooks
==> default: Running provisioner: chef_solo...
Generating chef JSON and uploading...
Running chef-solo...
[2015-01-14T00:42:25+00:00] INFO: Forking chef instance to converge...
[2015-01-14T00:42:25+00:00] WARN: 
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
SSL validation of HTTPS requests is disabled. HTTPS connections are still
encrypted, but chef is not able to detect forged replies or man in the middle
attacks.

To fix this issue add an entry like this to your configuration file:

```
  # Verify all HTTPS connections (recommended)
  ssl_verify_mode :verify_peer

  # OR, Verify only connections to chef-server
  verify_api_cert true
```

To check your SSL configuration, or troubleshoot errors, you can use the
`knife ssl check` command like so:

```
  knife ssl check -c /tmp/vagrant-chef-1/solo.rb
```

* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

[2015-01-14T00:42:25+00:00] INFO: *** Chef 11.16.4 ***
[2015-01-14T00:42:25+00:00] INFO: Chef-client pid: 20604
[2015-01-14T00:42:42+00:00] INFO: Setting the run_list to ["recipe[yum::remi]", "recipe[iptables]", "recipe[apache2]", "recipe[apache2::mod_php5]", "recipe[apache2::mod_ssl]", "recipe[mysql::server]", "recipe[mysql::ruby]", "recipe[php::package]", "recipe[wpcli]", "recipe[wpcli::install]", "recipe[vccw]"] from CLI options
[2015-01-14T00:42:42+00:00] INFO: Run List is [recipe[yum::remi], recipe[iptables], recipe[apache2], recipe[apache2::mod_php5], recipe[apache2::mod_ssl], recipe[mysql::server], recipe[mysql::ruby], recipe[php::package], recipe[wpcli], recipe[wpcli::install], recipe[vccw]]
[2015-01-14T00:42:42+00:00] INFO: Run List expands to [yum::remi, iptables, apache2, apache2::mod_php5, apache2::mod_ssl, mysql::server, mysql::ruby, php::package, wpcli, wpcli::install, vccw]
[2015-01-14T00:42:42+00:00] INFO: Starting Chef Run for test0114.local
[2015-01-14T00:42:42+00:00] INFO: Running start handlers
[2015-01-14T00:42:42+00:00] INFO: Start handlers complete.
==> default: Checking for host entries
==> default: adding to (/etc/hosts) : 192.168.33.10  test0114.local  # VAGRANT: 94c1170eb80690740d77cc2bfe2a0e8e (default) / b5891044-c120-4db6-bcdf-a5a9f0889bc9
MatsuoShoko-no-MacBook-Pro:0114 showw$ 

——————————————————
That’s all.
www/wordpress is empty.
It seems that processing is over on the way.

I think it is strange,when I try to use the same vagrantfile, sometimes succeed.
Could you give me some advice for me?

I use VirtualBox 4.3.8,Vagrant 1.5.1

**Comment by miya0001** [comment]
Please open VirtualBox.

![](https://www.evernote.com/shard/s21/sh/46a8caa2-da7d-496b-8fc2-6010c28b6c43/37d1a45dad3ed02ff3abdff7dbcf12e3/deep/0/Oracle-VM-VirtualBox-Manager.png)

Are there any unused virtual machine(s)?

If you have unused virtual machine(s), you should halt it.

**Comment by showw** [comment]
There isn't operating virtual machine. Everything is halt.

But, after I tried vagrant up several times, WordPress is installed.
It seems networking problem, probably.

Anyway, I appreciate your answer. 
I use it from now on.
