### ISSUE TITLE
403 on dump.php

### ISSUE THREAD

**Issue by blocka** [miya0001/vccw#54]
Not sure if this is a host specific issue or not, but I get a 403 on the dump.php file when its in wp-content. If I move it out to the root, it works fine.

**Comment by miya0001** [comment]
The problem happened on the local vagrant machine or production server?
Did you deploy with wordmove?

**Comment by blocka** [comment]
the production server, using wordmove.

On Thu, Jan 15, 2015 at 5:30 PM, Takayuki Miyauchi <notifications@github.com

**Comment by miya0001** [comment]
It looks a problem of the Wordmove.
I didn't know about the problem, thanks.

**Comment by blocka** [comment]
You're right...i'm not why I put the issue on this project.
